In [2]:
import numpy as np
print(np.zeros(2,int))

[0 0]


In [ ]:
np??



### A single raw integer in python  
> ```c
> struct _longobject {
>     long ob_refcnt;// handle memory allocation and deallocation
>     PyTypeObject *ob_type; // encode the type of the variable
>     size_t ob_size; // which specifies size of the following data members
>     long ob_digit[1]; // contain actual the integer value
> };
> ```

# ***Numpy can use only same type***

In [5]:
import numpy as np
hi = np.array([3.14,3,4,5])
print(hi)

[3.14 3.   4.   5.  ]


In [6]:
np.array([range(i,i+3) for i in range(3)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [7]:
np.zeros(10,dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,4,7),dtype = int)

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

In [26]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.full((3,4),2.7)

array([[2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.random.random((3,3))

array([[0.01373082, 0.5917009 , 0.08367932],
       [0.29820706, 0.02298571, 0.18218442],
       [0.7619816 , 0.19145463, 0.56900356]])

In [13]:
np.random.normal(0,1,(3,3))

array([[-1.88094358,  1.63988564, -1.92631766],
       [ 1.05656049, -0.11281747, -2.13564973],
       [-0.45902768, -0.73634846,  0.0778024 ]])

In [16]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.empty(3)

array([1.09469590e-311, 1.09469590e-311, 2.06999285e+161])

In [26]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (3,4))
x3 = np.random.randint(10,size = (3,4,5))

print("x3 ndim: " + str(x3.ndim))
print("x3 shape: " + str(x3.shape))
print("x3 size: " + str(x3.size))

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [27]:
print(x3.dtype)

int32


In [29]:
print(x3.itemsize, "bytes")

4 bytes


In [30]:
print("nbytes", x3.nbytes,"bytes")

nbytes 240 bytes


'D:\\begin\\Anaconda\\NOTEBOOK\\WILD\\DATASCIENCE'

In [19]:
import numpy as np
np.random.seed(3)

np.random.randint((5,5,1))

array([2, 0, 0], dtype=int32)

### Array Indexing: Accessing Single Elements

#### One-dimension

In [23]:
import numpy as np
x1 = np.array([5,6,6,44])
print(x1[1])

6


#### Mutiple-dimensioon

In [24]:
import numpy as np
x3 = np.random.randint(10,size = (2,3,4))
print(x3)
print(x3[1,2,3])

[[[9 3 8 8]
  [0 5 3 9]
  [9 5 7 6]]

 [[0 4 7 8]
  [1 6 2 2]
  [1 3 5 8]]]
8


<center>
    <h4>
        <strong>
            Array Slicing: Accessing Subarrays
        </strong>
    </h4>
</center>

##### *CONCATENATE*

In [45]:
import numpy as np
x = np.array([1,2,3])
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [32]:
import numpy as np
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
import numpy as np
x1 = np.arange(1,10).reshape((3,3))
x2 = np.arange(11,20).reshape((3,3))


total = np.concatenate([x1,x2]).reshape((3,6))
print(total)

[[ 1  2  3  4  5  6]
 [ 7  8  9 11 12 13]
 [14 15 16 17 18 19]]


In [46]:
import numpy as np
np.random.seed(0) # AVOID THE DUPLICATION OF SCENARIO
x1 = np.random.randint(100,size = (10))
x2 = np.random.randint(100,size = (10))


np.vstack([x1,x2]) # vertical concatenation

array([[44, 47, 64, 67, 67,  9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58, 65, 39, 87, 46, 88]], dtype=int32)

In [48]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(100,size = (10))
x2 = np.random.randint(100,size = (10))

np.hstack([x1,x2]) # horizontal stack

array([44, 47, 64, 67, 67,  9, 83, 21, 36, 87, 70, 88, 88, 12, 58, 65, 39,
       87, 46, 88], dtype=int32)

##### *SPILTTING*

In [49]:
x = np.random.randint(100,size = (8))
x1, x2, x3 = np.split(x,[3,5])
print(x1,x2,x3)

[81 37 25] [77 72] [ 9 20 80]


> split N -> N + 1 subarrays

In [52]:
grid = np.arange(16).reshape((4,4))
upper, lower = np.vsplit(grid,[2]) # SPLIT vertcally opposite to horizontally
print("UPPER:")
print(upper)
print("LOWER")
print(lower)

UPPER:
[[0 1 2 3]
 [4 5 6 7]]
LOWER
[[ 8  9 10 11]
 [12 13 14 15]]


<center>
    <h2>
        <strong>
            Array Slicing: Accessing Subarrays
        </strong>
    </h2>
</center>

In [54]:
import numpy as np
np.random.seed(0)

def compute_recporals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = np.random.randint(1,10,size = 5)
compute_recporals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [55]:
import numpy as np
np.random.seed(0)

def compute_recporals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/ values[i]
    return output

values = np.random.randint(1,10,size = 5)
%timeit compute_recporals(values)

12.4 μs ± 572 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
