In [2]:
import numpy as np
print(np.zeros(2,int))

[0 0]


In [4]:
np??

Type:        module
String form: <module 'numpy' from 'D:\\Anaconda\\Lib\\site-packages\\numpy\\__init__.py'>
File:        d:\anaconda\lib\site-packages\numpy\__init__.py
Source:     
"""
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the buil



### A single raw integer in python  
> ```c
> struct _longobject {
>     long ob_refcnt;// handle memory allocation and deallocation
>     PyTypeObject *ob_type; // encode the type of the variable
>     size_t ob_size; // which specifies size of the following data members
>     long ob_digit[1]; // contain actual the integer value
> };
> ```

# ***Numpy can use only same type***

In [5]:
import numpy as np
hi = np.array([3.14,3,4,5])
print(hi)

[3.14 3.   4.   5.  ]


In [6]:
np.array([range(i,i+3) for i in range(3)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [7]:
np.zeros(10,dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((3,4,7),dtype = int)

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

In [9]:
np.linspace(1,10,1000)

array([ 1.        ,  1.00900901,  1.01801802,  1.02702703,  1.03603604,
        1.04504505,  1.05405405,  1.06306306,  1.07207207,  1.08108108,
        1.09009009,  1.0990991 ,  1.10810811,  1.11711712,  1.12612613,
        1.13513514,  1.14414414,  1.15315315,  1.16216216,  1.17117117,
        1.18018018,  1.18918919,  1.1981982 ,  1.20720721,  1.21621622,
        1.22522523,  1.23423423,  1.24324324,  1.25225225,  1.26126126,
        1.27027027,  1.27927928,  1.28828829,  1.2972973 ,  1.30630631,
        1.31531532,  1.32432432,  1.33333333,  1.34234234,  1.35135135,
        1.36036036,  1.36936937,  1.37837838,  1.38738739,  1.3963964 ,
        1.40540541,  1.41441441,  1.42342342,  1.43243243,  1.44144144,
        1.45045045,  1.45945946,  1.46846847,  1.47747748,  1.48648649,
        1.4954955 ,  1.5045045 ,  1.51351351,  1.52252252,  1.53153153,
        1.54054054,  1.54954955,  1.55855856,  1.56756757,  1.57657658,
        1.58558559,  1.59459459,  1.6036036 ,  1.61261261,  1.62

In [10]:
np.full((3,4),2.7)

array([[2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7],
       [2.7, 2.7, 2.7, 2.7]])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.random.random((3,3))

array([[0.01373082, 0.5917009 , 0.08367932],
       [0.29820706, 0.02298571, 0.18218442],
       [0.7619816 , 0.19145463, 0.56900356]])

In [13]:
np.random.normal(0,1,(3,3))

array([[-1.88094358,  1.63988564, -1.92631766],
       [ 1.05656049, -0.11281747, -2.13564973],
       [-0.45902768, -0.73634846,  0.0778024 ]])

In [16]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.empty(3)

array([1.09469590e-311, 1.09469590e-311, 2.06999285e+161])

In [26]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10,size = 6)
x2 = np.random.randint(10,size = (3,4))
x3 = np.random.randint(10,size = (3,4,5))

print("x3 ndim: " + str(x3.ndim))
print("x3 shape: " + str(x3.shape))
print("x3 size: " + str(x3.size))

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [27]:
print(x3.dtype)

int32


In [29]:
print(x3.itemsize, "bytes")

4 bytes


In [30]:
print("nbytes", x3.nbytes,"bytes")

nbytes 240 bytes


'D:\\begin\\Anaconda\\NOTEBOOK\\WILD\\DATASCIENCE'

In [19]:
import numpy as np
np.random.seed(3)

np.random.randint((5,5,1))

array([2, 0, 0], dtype=int32)

### Array Indexing: Accessing Single Elements

#### One-dimension

In [23]:
import numpy as np
x1 = np.array([5,6,6,44])
print(x1[1])

6


#### Mutiple-dimensioon

In [24]:
import numpy as np
x3 = np.random.randint(10,size = (2,3,4))
print(x3)
print(x3[1,2,3])

[[[9 3 8 8]
  [0 5 3 9]
  [9 5 7 6]]

 [[0 4 7 8]
  [1 6 2 2]
  [1 3 5 8]]]
8


<center>
    <h4>
        <strong>
            Array Slicing: Accessing Subarrays
        </strong>
    </h4>
</center>